name: daro_flutter
description: Daro Flutter SDK
version: 1.0.2
homepage: https://guide.daro.so/ko/before-the-beginning
repository: https://github.com/delightroom/daro-ios-sdk
issue_tracker: https://github.com/delightroom/daro-ios-sdk/issues
topics:
  - ads
  - advertising
  - monetization

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: so.daro.flutter
        pluginClass: DaroFlutterPlugin
      ios:
        pluginClass: DaroFlutterPlugin
